# Giving up on this, I cannot find any documentation on how to use RBS properly...


class NetAddr::IPv4Net
class NetAddr::IPv6Net

module AussieStarlinkIPs
  type IpList = Array[NetAddr::IPv4Net | NetAddr::IPv6Net]

  # Fetch and parse a list directly from the Starlink feed.
  def self.fetch_list: () -> IpList 

  def self.parse_csv: (String file) -> IpList

  def self.is_aussie?: (IpList ip_list, String ip) -> bool 
end
